config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'

  resources :rooms do
    collection do
      get :toprooms
    end
    resources :articles
  end

  resources :articles do
    collection do
      get :top
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :room
  broadcasts_to :room
  # after_create_commit -> { broadcast_append_to room }
  # after_destroy_commit -> { broadcast_remove_to room }
  # after_update_commit -> { broadcast_replace_to room }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :articles
  #broadcasts
  #after_update_commit -> { broadcast_replace_to room }
  # after_create_commit -> { broadcast_append_to room }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_room, only: %i[new create]

  def top
    @articles = Article.order(:start).where(marked: true)
  end

  def new
    @article = @room.articles.new
  end

  def create
    @article = @room.articles.create!(article_params)

    respond_to do | format |
      format.turbo_stream
      format.html {redirect_to @room}
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def article_params
    params.require(:article).permit(:content, :marked)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]


  def toprooms
      @rooms = Room.order(:start).where(check: true)

  end

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        # format.turbo_stream

        format.html { redirect_to room_url(@room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        # format.turbo_stream

        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        # format.turbo_stream
        format.html { redirect_to room_url(@room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :check)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/articles/_article.html.erb
<p id="<%= dom_id article %>">
  <strong>Marked ? : </strong><%= article.marked %>
    <%= form_with(model: [ article.room, article ]) do | form | %>

        <%= form.check_box :marked %>
        <% end %>

  <%= article.created_at.to_s(:short) %>: <%= article.content %>
</p>
<p><%#= link_to, "top articles", top_articles_path %></p>
<%= link_to "top articles", top_articles_path, class: "nav-link" %>

app/views/articles/_form.html.erb
  <%= form_with(model: [ article.room, article ],
    data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset"}) do | form | %>
    <div class="field">
      <%= form.text_field :content %>
      <%= form.submit "send" %>
    </div>
  <% end %>

app/views/articles/crate.turbo_stream.erb
<%#= turbo_stream.append "articles", @article %>
<% #return hanled by cable %>

app/views/articles/create.turbo_stream.erb
<%#= turbo_stream.append "articles", @article %>
<% #return hanled by cable %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= turbo_frame_tag "new_article", target: "_top" do %>
  <%= form_with(model: [ @article.room, @article ],
    data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset"}) do | form | %>
    <div class="field">
      <%= form.text_field :content %>
      <%= form.submit "send" %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', @article.room %>

app/views/articles/top.html.erb
<h1 class="top">Top articles</h1>
    <%= link_to "Back to rooms", rooms_path %>


<div id="collecteds" class="cards">
  <% @articles.each do |article| %>
        <div class="card no_link">
      <%= link_to article do %>
          <%= render article %>
      <% end %>
        </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_checker.html.erb
 <%= form_with(model: room) do | form | %>
    <%= form.check_box :check %>
    <%= form.submit %>
  <% end %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <h3>_form room</h3>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
    <%= form.check_box :check %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
    <strong> Check ? : </strong>
    <%= room.check %>
        <%= render "checker", room: room %>
  </p>

</div>
<%= turbo_frame_tag "check_room", target: "_top" do %>
  <%= form_with(model: room,
    data: { controller: "toggle_check", action: "turbo:submit-end->toggle_check#toggle"}) do | form | %>
    <div class="field">
      <%= form.check_box :check %>
      <%= form.submit "send" %>
    </div>
  <% end %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= turbo_frame_tag "room" do %>
  <%= render "form", room: @room %>
<% end %>

<br>

<div>
  <%= link_to "Show this room", @room %>
  <%= link_to "Back to rooms", rooms_path, "data-turbo-frame": "_top" %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms index</h1>
<%= link_to "top rooms", toprooms_rooms_path, class: "nav-link" %>

<turbo_stream action="toast" message="Hello"></turbo_stream>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green" id="notice"><%= notice %></p>
<h1 class="show">Show</h1>
<p>Rooms show with turbo frames and turbo stream</p>
<ul>
  <li>turbo_frame_tag "room"</li>
  <li>turbo_frame_tag "new_article"</li>
  <li>turbo_stream_from @room</li>
</ul>

<%= turbo_stream_from @room %>
<%= turbo_frame_tag "room" do %>
<%= render @room %>
<small>turbo_frame_tag "room"</small>

  <p>
    <%= link_to "Edit this room", edit_room_path(@room) %> |
    <%= link_to "Back to rooms", rooms_path, "data-turbo-frame": "_top" %>
    <small><strong>link to :</strong> rooms_path, "data-turbo-frame": "_top"</small>
  </p>
<% end %>

<div id="articles">
  <%= render @room.articles %>
</div>

<div>
<br>
<%#= link_to "New article", new_room_article_path(@room) %>
  <%= turbo_frame_tag "new_article", src: new_room_article_path(@room), target: "_top" %>
  <small>turbo_frame_tag "new_article", src: new_room_article_path(@room), target: "_top"</small>
</div>
<%#= button_to "Destroy this room", @room, method: :delete %>

app/views/rooms/toprooms.html.erb
<h1 class="toprooms">Top rooms</h1>
    <%= link_to "Back to rooms", rooms_path %>


<div id="collecteds" class="cards">
  <% @rooms.each do |room| %>
        <div class="card no_link">
      <%#= link_to article do %>
          <%= render room %>
      <%# end %>
        </div>
  <% end %>
</div>